(require 'ruby-mode)
(require 'ruby-test)

 (setq ri-ruby-script "~/.emacs.d/vendor/20language/ri-emacs/ri-emacs.rb")
 (autoload 'ri "~/.emacs.d/vendor/20language/ri-emacs/ri-ruby.el" nil t)
 (add-hook 'ruby-mode-hook (lambda ()
                            ;;(ocal-set-key 'f1 'ri)
			    (local-set-key "\M-\C-i" 'ri-ruby-complete-symbol)
			    ;;(local-set-key 'f4 'ri-ruby-show-args)
			    ))

(require 'anything)
(require 'anything-rcodetools)
;; Command to get all RI entries.
(setq rct-get-all-methods-command "PAGER=cat qri -l")
;; See docs
(define-key anything-map "\C-z" 'anything-execute-persistent-action)
(require 'anything-dabbrev-expand)
(global-set-key "\M-/" 'anything-dabbrev-expand)
(define-key anything-dabbrev-map "\M-/" 'anything-dabbrev-find-all-buffers)
(require 'rcodetools)
(setq rct-find-tag-if-available nil)
(defun make-ruby-scratch-buffer ()
  (with-current-buffer (get-buffer-create "*ruby scratch*")
    (ruby-mode)
    (current-buffer)))
(defun ruby-scratch ()
  (interactive)
  (pop-to-buffer (make-ruby-scratch-buffer)))
(defun ruby-mode-hook-rcodetools ()
  (define-key ruby-mode-map "\M-\C-i" 'rct-complete-symbol)
  (define-key ruby-mode-map "\C-c\C-t" 'ruby-toggle-buffer)
  (define-key ruby-mode-map "\C-c\C-d" 'xmp)
  (define-key ruby-mode-map "\C-c\C-f" 'rct-ri))
(add-hook 'ruby-mode-hook 'ruby-mode-hook-rcodetools)

(require 'rails-lib)
(require 'rails-ruby)

(add-hook 'ruby-mode-hook
          (lambda()
            (add-hook 'local-write-file-hooks  
                      '(lambda()  
                         (save-excursion  
                           (untabify (point-min) (point-max))  
                           (delete-trailing-whitespace)  
                           )))  
            (set (make-local-variable 'indent-tabs-mode) 'nil)  
            (require 'rails-ruby)
            (require 'ruby-electric)  
            (ruby-electric-mode t)  
            (modify-syntax-entry ?! "w" (syntax-table))
            (modify-syntax-entry ?: "w" (syntax-table))
            (modify-syntax-entry ?_ "w" (syntax-table))
            (local-set-key (kbd "C-.") 'complete-tag)
            (local-set-key (kbd "C-:") 'ruby-toggle-string<>simbol)
            (local-set-key (kbd "RET") 'ruby-newline-and-indent)))

